swagger: '2.0'
info:
  title: Reactions microservice
  description: Operations to menage reactions
  version: 1.0.0
host: 127.0.0.1
schemes:
  - http
  - https
paths:
  /reactions/story_id:
    get:
      description: Return the list of reactions of a given story
      operationId: getReactions
      produces:
        - application/json
      responses:
        '200':
          description: A JSON array of JSON objects containing reactions data
          schema:
            type: array
            items:
              $ref: '#/definitions/reactions'
  /counters/story_id:
    get:
      description: Return the list of counters of the given story
      operationId: getCounters
      produces:
        - application/json
      responses:
        '200':
          description: A JSON array of JSON objects containing counters data
          schema:
            type: array
            items:
              $ref: '#/definitions/story'

  /new:
    post:
      description: Initializie a new counter when a new story has been published
      operationId: newStory
      consumes:
        - application/json
      parameters:
        - in: body
          name: story_id
          schema:
            $ref: '#/definitions/story'
      produces:
        - application/json
      responses:
        '200':
          description: Counters created successfully
  /react:
    post:
      description: Insert a new reaction
      operationId: react
      consumes:
        - application/json
      parameters:
        - in: body
          name: story_id
          schema:
            items:
              $ref: '#/definitions/react'
          required: True
          description: The value that identifies the story
      produces:
        - application/json
      responses:
        '200':
          description: Reaction submitted

  /stats:
    post:
      description: Insert a new reaction
      operationId: stats
      consumes:
        - application/json
      parameters:
        - in: body
          name: story_id
          schema:
            items:
              $ref: '#/definitions/react'
          required: True
          description: The value that identifies the story
      produces:
        - application/json
      responses:
        '200':
          description: Reaction submitted


definitions:
  reactions:
    type: object
    properties:
      id:
        type: integer
      reactor_id:
        type: integer
      story_id:
        type: integer
      reaction_type_id:
        type: integer
      reaction_type:
        type: integer
      marked:
        type: integer

  counters:
    type: object
    properties:
      reaction_type_id:
        type: integer
      story_id:
        type: integer
      counter:
        type: integer

  story:
    type: object
    properties:
      story_id:
        type: string

  react:
    type: object
    properties:
      story_id:
        type: string
      reaction_caption:
        type: string